In [17]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import *
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB, BernoulliNB

In [18]:
data = pd.read_csv('data/PO1.csv')

In [19]:
data.head(10)

     C1    C2         C3    C4        C5        C6          C7  N1 Decision
0   mid   low  excellent   mid    stable    stable      stable  15        A
1   mid  high  excellent  high    stable    stable      stable  10        S
2  high   low  excellent  high    stable    stable  mod-stable  10        A
3   mid   low       good  high    stable  unstable  mod-stable  15       A
4   mid   mid  excellent  high    stable    stable      stable  10        A
5  high   low       good   mid    stable    stable    unstable  15        S
6   mid   low  excellent  high    stable    stable  mod-stable   5        S
7  high   mid  excellent   mid  unstable  unstable      stable  10        S
8   mid  high       good   mid    stable    stable      stable  10        S
9   mid   low  excellent   mid  unstable    stable  mod-stable  10        S

In [21]:
X = data.drop('Decision', axis=1)
X.head(5)

y = data.Decision
y.head(5)

0     A
1     S
2     A
3    A
4     A
Name: Decision, dtype: object

In [22]:
for i in X:
    print(set(X[i]))

{'low', 'high', 'mid'}
{'low', 'high', 'mid'}
{'excellent', 'good'}
{'low', 'high', 'mid'}
{'stable', 'unstable'}
{'stable', 'mod-stable', 'unstable'}
{'stable', 'mod-stable', 'unstable'}
{7, 10, 5, 15}

In [33]:
print(set(y))

{0, 1, 2, 3}

In [26]:
enc = LabelEncoder()
for i in X:
    X[i] = enc.fit_transform(X[i])
y = enc.fit_transform(y)

In [27]:
X.head(10)

   C1  C2  C3  C4  C5  C6  C7  N1
0   2   1   0   2   0   1   1   3
1   2   0   0   0   0   1   1   2
2   0   1   0   0   0   1   0   2
3   2   1   1   0   0   2   0   3
4   2   2   0   0   0   1   1   2
5   0   1   1   2   0   1   2   3
6   2   1   0   0   0   1   0   0
7   0   2   0   2   1   2   1   2
8   2   0   1   2   0   1   1   2
9   2   1   0   2   1   1   0   2

In [28]:
y[1:10]

array([3, 0, 1, 0, 3, 3, 3, 3, 3])

In [29]:
h_enc = OneHotEncoder(sparse=False)
X_enc = h_enc.fit_transform(X)

In [35]:
X_enc

array([[ 0.,  0.,  1., ...,  0.,  0.,  1.],
       [ 0.,  0.,  1., ...,  0.,  1.,  0.],
       [ 1.,  0.,  0., ...,  0.,  1.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  0.,  0.,  1.],
       [ 0.,  0.,  1., ...,  0.,  1.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  1.]])

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X_enc, y, test_size=0.2, random_state=2016)

In [37]:
clf = BernoulliNB()
clf = clf.fit(X_train, y_train)

In [39]:
clf.score(X_test, y_test)

0.61111111111111116

In [40]:
X

    C1  C2  C3  C4  C5  C6  C7  N1
0    2   1   0   2   0   1   1   3
1    2   0   0   0   0   1   1   2
2    0   1   0   0   0   1   0   2
3    2   1   1   0   0   2   0   3
4    2   2   0   0   0   1   1   2
5    0   1   1   2   0   1   2   3
6    2   1   0   0   0   1   0   0
7    0   2   0   2   1   2   1   2
8    2   0   1   2   0   1   1   2
9    2   1   0   2   1   1   0   2
10   2   2   1   2   0   1   1   3
11   2   1   1   0   0   1   0   2
12   0   0   0   0   1   1   2   3
13   2   0   1   2   1   1   0   2
14   2   1   1   0   1   2   1   3
15   0   0   0   0   1   1   2   2
16   1   0   1   0   1   1   0   3
17   2   1   1   0   1   1   1   2
18   2   0   1   2   1   1   2   3
19   2   2   1   2   0   1   1   2
20   1   0   1   2   1   1   1   3
21   1   2   0   0   1   1   2   2
22   2   2   1   2   1   1   2   3
23   2   2   1   2   1   1   1   2
24   0   0   1   2   0   1   0   2
25   1   2   1   2   1   1   1   2
26   0   2   1   1   0   1   0   2
27   1   2   0   0   0   1   0   2
28   2   2   0   2   0   1   2   3
29   2   2   1   2   1   1   2   2
..  ..  ..  ..  ..  ..  ..  ..  ..
57   2   0   1   2   0   1   0   2
58   2   0   1   2   1   1   2   2
59   2   1   0   0   0   1   1   2
60   2   2   1   2   0   1   2   2
61   2   1   0   2   0   1   2   2
62   0   2   0   2   1   2   2   2
63   2   2   1   0   0   1   1   2
64   2   1   0   2   1   1   1   2
65   2   2   0   2   1   1   1   2
66   2   2   0   0   0   1   1   2
67   2   2   0   1   0   1   1   2
68   1   1   0   2   0   1   1   2
69   2   2   0   2   0   1   0   2
70   2   2   0   0   0   1   1   2
71   2   1   0   0   0   1   0   2
72   1   2   1   2   0   1   2   2
73   2   2   0   2   0   1   0   2
74   2   2   0   2   0   1   2   2
75   2   2   0   2   1   2   1   2
76   2   2   1   0   0   1   1   2
77   2   2   0   2   0   1   1   3
78   2   2   0   2   0   1   1   2
79   2   1   1   2   0   1   2   2
80   0   2   0   2   1   1   2   0
81   2   2   0   2   0   1   2   2
82   2   2   0   2   1   1   1   2
83   2   2   0   2   1   1   1   3
84   2   2   1   2   1   1   1   3
85   2   2   0   2   1   1   1   2
86   2   2   1   2   1   1   1   3

[87 rows x 8 columns]

In [46]:
X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(X, y, test_size=0.2, random_state=2016)

In [43]:
clf_m = MultinomialNB()
clf_m = clf_m.fit(X_train_m, y_train_m)

In [45]:
clf_m.score(X_test_m, y_test_m)

0.66666666666666663

In [49]:
X_train_m.shape

(69, 8)

In [50]:
X_test_m.shape

(18, 8)